workflows:
  android-workflow:
    name: Android Workflow (No Signing)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.24.5
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
      - name: Build unsigned AAB
        script: |
          flutter build appbundle --debug
    artifacts:
      - build/app/outputs/bundle/debug/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
