workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.22.0
      xcode: latest
    scripts:
      - name: Clean and get packages
        script: |
          flutter clean
          flutter pub get
      - name: Build AAB
        script: |
          flutter build appbundle --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
