workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.22.0
      vars:
        KEYSTORE_PASSWORD: "MySecurePassword123!"
        KEY_ALIAS: "upload"
        KEY_PASSWORD: "MySecurePassword123!"
    scripts:
      - name: Create keystore automatically
        script: |
          keytool -genkey -v -keystore $HOME/upload.keystore \
            -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 \
            -alias $KEY_ALIAS \
            -storepass $KEYSTORE_PASSWORD \
            -keypass $KEY_PASSWORD \
            -dname "CN=Reface Beauty, OU=Reface Beauty, O=Reface Beauty, L=Seoul, ST=Seoul, C=KR"
      
      - name: Set up key.properties for Android
        script: |
          cat > $CM_BUILD_DIR/android/key.properties <<EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEY_PASSWORD
          keyAlias=$KEY_ALIAS
          storeFile=$HOME/upload.keystore
          EOF
      
      - name: Clean and get Flutter dependencies
        script: |
          rm -f pubspec.lock
          flutter clean
          flutter pub get
      
      - name: Build signed Release AAB
        script: |
          flutter build appbundle --release
    
    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - $HOME/upload.keystore
    
    publishing:
      email:
        recipients:
          - seossine@gmail.com
