workflows:
  android-workflow:
    name: Android Workflow (Debug Build)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.22.0
      xcode: latest
    scripts:
      - name: Clean and reset dependencies
        script: |
          rm -f pubspec.lock
          flutter clean
          flutter pub get
      - name: Build Debug AAB (No signing required)
        script: |
          flutter build appbundle --debug
    artifacts:
      - build/app/outputs/bundle/debug/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
